OnMouseMove             =NULL;
OnMouseWheel            =NULL;
OnMouseLeftDown         =NULL;
OnMouseLeftUp           =NULL;
OnMouseLeftDoubleClick  =NULL;
OnMouseMidDown          =NULL;
OnMouseMidUp            =NULL;
OnMouseMidDoubleClick   =NULL;
OnMouseRightDown        =NULL;
OnMouseRightUp          =NULL;
OnMouseRightDoubleClick =NULL;
			
OnJoystickDown			=NULL;
OnJoystickPress			=NULL;
OnJoystickUp  			=NULL;

OnKeyDown       		=NULL;
OnKeyPress				=NULL;
OnKeyUp         		=NULL;
			
OnChar          		=NULL;

OnEvent         		=NULL;